### PR TITLE
Fix for setup instructions

### PR DESCRIPTION
**Pull request by nullromo**
Added a line to the setup instructions on the README. Also fixed a quotation at the end of the setup file.

### CODE REVIEW

**Review by davidmoten — COMMENTED** [review]
Why open up 8080 when we just want https?

**Comment by nullromo** [comment]
Because port 8080 is the port that Jenkins runs on. I set it up without access to that port and when I typed http://......amazonaws.com/ into my web browser, I didn't get anything. Then when I added access to that port and typed http://......amazonaws.com/:8080 into my web browser, it worked. Here is the resource I used to figure this out: https://d1.awsstatic.com/Projects/P5505030/aws-project_Jenkins-build-server.pdf The bottom of page 3 and the top of page 9 suggest this.

**Comment by davidmoten** [comment]
>Because port 8080 is the port that Jenkins runs on

Yep you are right but the whole point of this project is to set up *https* access so we want to disable http access. What happens is Apache listens on 443 (default https port) and forwards requests to 8080 internally. You shouldn't open up 8080 because it is insecure (your login is in plain text so you are exposed to attack).

**Comment by davidmoten** [comment]
You should try your url with https in front.

**Comment by nullromo** [comment]
Ah thank you. I was unaware of the standards for and differences between https vs http. When I try with https, however, I get a security certificate that is not trusted by the browser. I'll close this PR.

**Pull request closed without merging**
